package database;

import lombok.*;

import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * Class used for creating DB Frame entity (table).<br>
 * All setters and getters are automatically generated by lombok.<br>
 * Both NoArgsConstructor constructor and AllArgsConstructor constructor are also generated automatically.
 *
 * @author Marcin Hebdzynski
 *
 */
@Entity
@Getter @Setter @NoArgsConstructor @AllArgsConstructor
public class DB_Frame {

    @Id
    int frameID;
    String material;
}
