package database;

import lombok.*;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Class used for creating DB Profile entity (table).<br>
 * All setters and getters are automatically generated by lombok.<br>
 * Both NoArgsConstructor constructor and AllArgsConstructor constructor are also generated automatically.<br>
 * Additionally lombok is used for overwriting ToString method.
 *
 * @author Patryk Dunajewski
 *
 */
@Entity
@Getter @Setter @NoArgsConstructor @AllArgsConstructor @ToString
public class DB_Profile {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    private String nick;
    private String password;
    private String name;
    private String surname;
    private int age;
    private float money;

    /**
     * Constructor needed apart from provided by lombok, because of id being auto-generated
     *
     * @param nick unique nick like mrPatrick98 (private, string value)
     * @param password password (without any restriction) (private, string value)
     * @param name name of the user (private, string value)
     * @param surname surname of the user (private, string value)
     * @param age age of the user, can also be done with date (private, int value)
     * @param money for the beginning of the project all of the users must insert how much money they have (private, float value)
     */
    public DB_Profile(String nick, String password, String name, String surname, int age, float money) {
        this.nick = nick;
        this.password = password;
        this.name = name;
        this.surname = surname;
        this.age =age;
        this.money = money;
    }
}
