package threads;

import lombok.*;
import lsea.Bike;

/**
 * Class that is used to create list with bikes objects and rate of it <br>
 * implements Comparable (RateArr)<br>
 * All setters and getters are automatically generated by lombok.<br>
 * Both NoArgsConstructor and AllArgsConstructor are also generated automatically.
 *
 * @author Patryk Dunajewski
 */
@Getter @Setter @NoArgsConstructor @AllArgsConstructor
public class RateArr implements Comparable<RateArr>{

    /*** bike->object of the bike class, it is one bike offer(private, Bike)*/
    private Bike bike;
    /*** rate->rate of the bike (private int)*/
    private int rate;

    /***override compareTo method*/
    @Override
    public int compareTo(RateArr o) {
        int result = Integer.compare(this.getRate(), o.getRate());
        return -result;
    }

    /*** override of toString method, so RateArr can be printed*/
    @Override
    public String toString() {
        return "RateArr[bike= "+bike.getNameOI()+" rate= "+rate+"]";
    }
}
